#+OPTIONS: toc:nil
#+OPTIONS: tex:dvipng

#+TITLE: Statistical Mechanics
#+AUTHOR: David A. Ventimiglia
#+EMAIL: dventimi@gmail.com

#+HTML_HEAD_EXTRA: <style type="text/css">
#+HTML_HEAD_EXTRA: dd, dt {text-align: center;}
#+HTML_HEAD_EXTRA: </style>

- What is the relationship between $C_p$ and $C_v$? [fn::Prat 4.2] :: 

     $C_p = C_v + 1$ 

- What useful relation ivolves the ratio of $C_p/C_v$? :: 

     $PV^{\gamma}\bigr\rvert_{N,x} = constant$

     where $\gamma = C_p\bigr\rvert_{C_v}$

- How is the pressure defined and what is an expression for it in the Grand Canonical Ensemble? [fn::Pratt 1.5] :: 

     Pressure is the dependence of the thermodynamic potentials upon the
     volume.

     $P(\mu, T, V) = \frac{\partial}{\partial_v}\Omega_{GC}(\mu/T, T, V)$

- In the classical limit $\mu < 0$.  What does it mean for Bosons if $\mu > 0$? [fn::Pratt 2.3] :: 

     It means nothing.

     For $\mu > 0$, $f(\epsilon)$ becomes negative for Bosons, which is
     non-physical.

- What is the condition for Bose condensation to occur (/non-relativistic/)? [fn::Pratt 2.3] ::

     As $\rho$ increases, $\mu$ approaches 0 from below.  If $\mu$
     reaches 0 at a finite density, condensation will occur.  That is,

     $\mu_{CONDENSE} = 0$

     $\rho(\mu_{CONDENSE}) = \rho_{CRIT}$

- What is the condition for Bose condensation to occur (/relativistic/)? [fn::Pratt 2.3] ::

     $\mu_{CONDENSE} = m$

- What is the Hamiltonian for a single spin in the Ising Model, in the mean-field limit? [fn::Pratt 2.5] ::

     $\mathcal{H}_i = -qJ\langle\rho\rangle\rho_i - \mu B \rho_i$

- Give the general expression for Boson density at 0 chemical potential (/non-relativistic/). [fn::Pratt 2.3] ::

     $\rho\bigr\rvert_{\mu=0} = (2J+1)
     \frac{(mT)^{D/2}}{(2\pi\hbar)^D} \bigg( \int d^D x e^{-x^2/2}
     \bigg) \sum_{n=1}^{\infty} n^{-D/2}$

- Under what circumstances wil there be---or not be---Bose condensation? [fn::Pratt 2.3] ::

     $\rho\bigr\rvert_{\mu=0} \sim \frac{p^{D-1} dp}{\beta \epsilon (p)} \sim \frac{p^{D-1} dp}{\beta p^n}$

     \begin{equation*}
     n = 
     \begin{cases}
     2 & non-relativistic \\
     1 & relativistic
     \end{cases}
     \end{equation*}

     Therefore, for $D-1 < n$, $\rho\bigr\rvert_{\mu=0}$ diverges as
     $p \to 0$.  So, for condensation to occur,

     \begin{equation*}
     D \rangle
     \begin{cases}
     2 & non-relativistic \\
     1 & relativistic
     \end{cases}
     \end{equation*}

- For a Boson gas whose density $\rho$ has exceeded the condensation critical density $\rho_{c} = \rho(\mu = 0)$, what is the density of the condensate? [fn::Pratt 2.3] ::

     $\rho_{CONDENSATE} = \rho - \rho_c$

- What are the number of ways to arrange $N_S$ systems inf configurations $n_0$, $n_1$, $n_2$, ... where $n_i$ is the number of systems in configuration $i$ ? [fn::Pratt 1.1] ::

     $I = \frac{N_s!}{n_0! n_1! ...}$

     $I$ is defined by Pratt as "ignorance."

- What are the stages of the Carnot cycle? [fn::Pratt 4.2] ::

  1. Isothermal expansion at $T_H$:  absorbing heat $Q_H$
  2. Isentropic expansion to $T_C$:  $PV^{\gamma}\bigr\rvert_{before} = PV^{\gamma}\bigr\rvert_{after}$
  3. Isothermal compression at $T_C$:  exhausting heat at $Q_C$
  4. Isentropic compression to $T_H$:  $PV^{\gamma}\bigr\rvert_{before} = PV^{\gamma}\bigr\rvert_{after}$

- What work is done by a Carnot cycle? [fn::Pratt 4.2] ::

     $W = Q_H - Q_C$

- Derive a useful expression for the pressure for systems whose dimensions are much larger than any correlations. [fn::Pratt 1.5] ::

  1. $\Omega \propto V$ and \Omega_{GC} = PV$
  2. $P V = T ln Z_{GC} = T S - \langle E \rangle + \mu \langle Q \rangle$

- What is $Z_{int}$ for a one-dimensional harmonic oscillator? [fn::Pratt 4.2] ::

     $Z_{int} = 1 + e^{-\beta \hbar \omega} + e^{-2 \beta \hbar \omega} \ldots$

- What is the average internal energy of a one-dimensional harmonic oscillator?  [fn::Pratt 4.2] ::

     $\langle E/N \rangle = \hbar \omega \frac{e^{-\beta\hbar\omega}}{1 - e^{-\beta\hbar\omega}}$

     \begin{equation*}
     \langle E/N \rangle = 
     \begin{cases}
     \hbar \omega e^{-\hbar\omega/T} & T \ll \hbar\omega \\
     T & T \gg \hbar\omega
     \end{cases}
     \end{equation*}

- How is the Carnot Efficiency $e$ defined?  [fn::Pratt 4.3] ::

     $e = \frac{W}{Q_H} = \frac{Q_H - Q_C}{Q_H} = 1 - \frac{Q_C}{Q_H}
     = 1 - \frac{T_C}{T_H}$

- In the absence of collisions, what is the entropy of a dilute gas of Fermions, independent of assumptions about thermalization?  [fn::Pratt 4.7] ::

     \[ = (2J+1) \int {\frac{d^3p d^3r}{(2\pi\hbar)^3} \big\{-(1-f) ln
     (1-f) - f ln f\big\}}\]

     $f$ is the probability of a phase space cell containing a
     Fermion, not assumed to be a Fermi-Dirac distribution.

- Why can a one-dimensional Ising Model not undergo spontaneous magnetization?  [fn::Pratt 5.3] ::

     In one-dimension, only one spin need flip in order to break a
     chain of spins, so the penalty for doing so is finite.

- What is the partition function for the one-dimensional Ising Model?  [fn::Pratt 5.3] ::

     \begin{eqnarray*}
     Z = \sum exp \big\{\beta J (\bar{\sigma_1}\bar{\sigma_2}+\bar{\sigma_2}\bar{\sigma_3}+\ldots+\bar{\sigma_n}\bar{\sigma_1}) + \\ 
         \beta \mu B (\bar{\sigma_1+\sigma_1+\ldots+\sigma_n}) \big\}
     \end{eqnarray*}

- Express the partition function for the one-dimensional Ising Model as a product of matrix elements.  [fn::Pratt 5.3] ::

     \[ Z = \sum \langle\sigma_1\rvert\sigma_{12}\rvert\sigma_2\rangle
     \langle\sigma_2\rvert\sigma_{23}\rvert\sigma_3\rangle \ldots
     \langle\sigma_n\rvert\sigma_{n1}\rvert\sigma_1\rangle \]

     \begin{eqnarray*}
     P_{i,i+1} = exp \beta \big\{J\sigma_i\sigma_{i+1} + \frac{1}{2}\mu\beta(\sigma_i+\sigma_{i+1})\big\} \\
     = \left(
     \begin{array}{cc}
     e^{\beta(J+\mu\beta)} & e^{-\beta J} \\
     e^{-\beta J} & e^{\beta(J-\mu\beta)}
     \end{array} \right)
     \end{eqnarray*}

- In the one-dimensional Ising Model, what are the eigenvalues of the probability matrix $P_{i,i+1}$?  [fn::Pratt 5.3] ::

     \[\lambda_\pm = e^{\beta J} cosh (\beta\mu B) \pm \sqrt{e^{2\beta
     J} sinh^2(\beta\mu B) + e^{-2\beta J}}\]

- In terms of the eigenvalues of the one-dimensional Ising Model's probability matrix $P_{i,i+1}$, what is the partition function?  [fn::Pratt 5.3] ::

     \[ Z = \lambda_+^n + \lambda_-^n \]

- What is the energy of the $n^{th}$ level of a simple one-dimensional harmonic oscillator?  [fn::Pratt 4.2] ::

     \[ \epsilon_{V \rvert B} = n \hbar \omega \]

- What is the entropy per system, in terms of $I$ ?  [fn::Pratt 1.1] ::

     \[ S \equiv \frac{1}{N_s} ln I \]

- What are the first two terms of the Stirling Approximation?  [fn::Pratt 1.1] ::

     \[ \lim_{N\to 0} ln N! \approx N ln N - N \]

- How is the entropy defined with respect to the probability of being in any particular state?  [fn::Pratt 1.1] ::

     \[ S \equiv -\sum_i p_i ln p_i \]

- What is the "Fundamental Thermodynamic Relation?"  [fn::Pratt 1.6] ::

     In the Grand Canonical Ensemble,

     \[ TdS = PdV + dE -\mu dQ \]

- What is the quantity to be extremized at equilibrium, under various constraints?  [fn::Pratt 1.7] ::

  1. Fixed $E, V, Q$:  $max S(x, E, V, Q)$
  2. Fixed $Q, V, T$:  $max F(x, T, V, Q)$
  3. Fixed $\mu, T, V$:  $max P(x, \mu, T, V)$
  4. Fixed $T, Q, P$:  $max G(x, T, Q, P)$

     $x$ is some order parameter we adjust to find the extremum.

- What is the /log/ of the partition function for the one-dimensional Ising Model, for many sites?  [fn::Pratt 5.3] ::

     \[ln Z = n ln(\lambda_+) + ln\Big[1 +
     (\frac{\lambda_-}{\lambda_+})^n\Big]\]

     As $n \to \infty$, 

     $ln Z \to n ln \lambda_+$

- In the Van der Waals equation-of-state, how is the critical temperature defined?  [fn::Pratt 3.3] ::

     \[ \frac{dP}{dV} = 0 \]

     and

     \[ \frac{d^2 P}{dV^2} = 0 \]

     \[ \Rightarrow T_c = \frac{8}{27} a \rho_s \]

- How do we use the method of Lagrange Multiplers to maximaze the entropy under the constraint that the system must be in /some/ state?  [fn::Pratt 1.1] ::

  1. \[ \frac{\partial}{\partial p_i} \Big(-\sum_j p_j ln p_j -
     \lambda \Big[\sum_j p_j - 1\Big] \Big) = 0 \]
  2. \[ \sum_j p_j - 1 = 0 \]
  3. \[ ln p_i = -\lambda - 1 \]
  4. \[ p_i = e^{-\lambda-1} \]

- What is the probability of a system being in a particular state, if we use Lagrange multipliers to constrain the average energy and average number of particles?  [fn::Pratt 1.3] ::

     \begin{eqnarray}
     p_i = e^{-1-\lambda-\beta\epsilon_i-\alpha Q_i} \\
     \beta = 1/T \\
     \alpha = -\beta\mu = -\mu/T
     \end{eqnarray}

- How does the partition function relate to the probabilities for the states of a system?  [fn::Pratt 1.4] ::

     It is the normalization factor:

     \begin{eqnarray}
     p_i = \frac{1}{Z} e^{-\beta\epsilon_i-\alpha Q_i} \\
     Z = e^{1+\lambda} = \sum_i e^{-\beta\epsilon_i - \alpha Q_i} \\
     ln Z = 1 + \lambda
     \end{eqnarray}

- What is the average spin in the Ising Model under the mean-field approximation, with no external field?  [fn::Pratt 5.2] ::

     \[ \langle\sigma\rangle = tanh (\beta q J \langle\sigma\rangle) \]

- What is the Taylor expansion for $tanh x$ for small $x$ ?  [fn::Pratt 5.2] ::

     \[ tanh x \approx x - \frac{1}{3}x^3 \]

- What is the density of a Fermi gas at $T=0$ ?  [fn::Pratt 2.4] ::

     Because the Fermi-Dirac distribution function $f$ at $T=0$ is a
     step function about $\mu$,

     \[ \rho(\mu, T=0) = \int_0^{\mu} d\epsilon
     \frac{\mathcal{D}(\epsilon)}{V} \]

- What is the Gibb's free energy?  [fn::Pratt 1.8] ::

     In the Grand Canonical Ensemble

     \[ G = E + PV - TS = \mu Q \]

- What is the density of single party states for a free particle?  [fn::Pratt 2.1] ::

     \begin{eqnarray}
     \mathcal{D}(\epsilon) = \frac{dN}{d^3x d^3p} = \frac{1}{(2\pi\hbar)^3} & \text{(3-D)} \\
     \mathcal{D}(\epsilon) = \frac{dN}{d^Dx d^Dp} = \frac{1}{(2\pi\hbar)^D} & \text{(General)}
     \end{eqnarray}

- What is the energy of the $l^{th}$ excited level of a diatomic rotator with moment of inertia $I$ ?  [fn::Pratt 4.2] ::

     \[ \epsilon_{rot} = \frac{\hbar^2 l(l+1)}{2I} \]

- What is the internal partition function for a diatomic rotator?  At high and low $T$ limits?  [fn::Pratt 4.2] ::

     \begin{eqnarray}
     Z_{rot} = \sum_{l=0}^{\infty}(2l+1)e^{-\beta\hbar^2\frac{l(l+1)}{2I}} \\
     z_{rot} =
     \begin{cases}
     e^{-\beta\hbar^2/2I} & T \ll \hbar^2/I \\
     IT/\hbar^2 & T \gg \hbar^2/I
     \end{cases}
     \end{eqnarray}

- How is the Fermi momentum $p_f$ typically defined?  [fn::Pratt 2.4] ::

     It is defined in 3-D by

     \begin{eqnarray*}
     \rho = (2J+1)\frac{1}{(2\pi\hbar)^3}\frac{4\pi}{3}p^3_f & \text{at T=0} \\
     \end{eqnarray*}

- What are the average energy and average particle number, in terms of the partition function?  [fn::Pratt 1.4] ::

     \begin{eqnarray}
     \langle E \rangle = -\frac{\partial}{\partial\beta} ln Z \\
     \langle Q \rangle = -\frac{\partial}{\partial\alpha} ln Z = \frac{\partial}{\partial(\beta\mu)} ln Z
     \end{eqnarray}

- In the one-dimensional Ising Model, what is the average spin?  [fn::Pratt 5.3] ::

     \[ \langle \sigma \rangle = \frac{1}{h}\Big(\frac{d ln
     Z}{d(\beta\mu B)}\Big) \]

- What form does a particle's wavefunction take after interacting with a spherical potential?  [fn::Pratt 3.2] ::

     \[\psi (r\to\infty) \sim
     \frac{e^{i\delta}}{pr}sin\Big(\frac{pr}{\hbar}-l\pi + \delta
     \Big) \]

- What are the conditions for phase coexistence?  [fn::Pratt 3.3] ::

     \begin{eqnarray}
     T_{gas} = T_{liq} \\
     P_{gas} = P_{liq} \\
     \mu_{gas} = \mu_{liq}
     \end{eqnarray}

- How do the Maxwell criteria express the condition that $\mu_{gas} = \mu_{liq}$ ?  [fn::Pratt 3.3] ::

     \[P_{gas}V_{gas} - P_{liq}V_{liq} - \int_{V_{liq}}^{V_{gas}} PdV = 0 \]

- What is the Grand Canonical partition function for a system of non-interacting free particles (i.e, a gas)? [fn::Pratt 2.1] ::

     \[Z_{GC} = \prod_p z_p\]

     where 

     \[z_p = \sum_{n_p} e^{-n_p(\beta\epsilon_p - \beta\mu q)}\]

     $n_p$ is the number of particles of charge $q$ in momentum mode $p$.

     \begin{eqnarray*}
     n_p \in [0, 1] & \text{Fermions} \\
     n_p \in [0, 1, 2, \ldots] & \text{Bosons}
     \end{eqnarray*}

- How is the latent heat defined?  [fn::Pratt 3.4]  ::

     During a phase transition $L=T\Delta S$ where,

     \[\Delta S = \Big(\frac{S}{N}\Big)_{gas} - \Big(\frac{S}{N})_{gas}\]

- What is $ln Z_{GC}$ for a gas of non-interacting particles?  [fn::Pratt 2.1]  ::

     \begin{eqnarray*}
     ln Z_{GC} & = & \sum_p ln z_p = \int \mathcal{D}(\epsilon) ln z_p d^3pd^3x \\
     & = & \int d^3x \int \frac{d^3p}{(2\pi\hbar)^3} (2J+1) ln z_p \\
     & = & \int \frac{Vd^3p}{(2\pi\hbar)^3 (2J+1) ln z_p}
     \end{eqnarray*}

     including spin multiplicity factor $(2J+1)$

- What is the density of states for a particle whose wavefunction has undergone a phase shift by a spherically-symmetric potential of radius $R$ ?  [fn::Pratt 3.2]  ::

     \begin{eqnarray*}
     \mathcal{D}(p) = \frac{dn}{dp} = \frac{(2l+1)}{\pi}\Big(\frac{R}{\hbar} + \frac{d\delta}{dp} \Big) \\
     \mathcal{D}(p) = \frac{dn}{d\epsilon} = \frac{(2l+1)}{\pi}\Big(\frac{R}{\hbar}\frac{m}{p} + \frac{d\delta}{d\epsilon}\Big)
     \end{eqnarray*}

# Local Variables:
# org-html-postamble: nil
# End:
