manuscript.epub:  manuscript.html
	ebook-convert $< $@ --page-breaks-before="//*[name()='h1' or name()='h2' or name()='dd' or name()='dt']" --cover=cover.jpg

clean:
	rm manuscript.epub manuscript.html

